### ISSUE TITLE
Pi-kvm image for Blikvm v4

### ISSUE THREAD

**Issue by jcastro** [RainCat1998/Bli-PiKVM#1]
Hi!

I've tried to follow up the instructions but I'm finding some problems after the second time executing the script, aiofiles is missing but looks like it's installed.

Are you able to maybe expand on the instructions or provide a flasheable image for the SD card? Thanks

<img width="937" alt="SCR-20240519-dcis" src="https://github.com/RainCat1998/Bli-PiKVM/assets/190036/3620431b-d3fa-4498-80db-274871dfb1b9">
<img width="1393" alt="SCR-20240519-dcji" src="https://github.com/RainCat1998/Bli-PiKVM/assets/190036/38435ec4-7f5e-46ae-a70f-7a84530d7296">

**Comment by jcastro** [comment]
I got it installed by running these commands
```
sudo pip install --force-reinstall aiofiles
sudo pip install --force-reinstall gpiod
```

**Comment by dw5** [comment]
for me i also had to do
sudo pip install --force-reinstall pygments

i think i'll host ready for use updated blikvm and additionally pikvm sd card image

**Comment by RainCat1998** [comment]
@jcastro  https://zcwrego195.feishu.cn/drive/folder/fldcntj64syIznoYuTdRFattP2f

**Comment by RainCat1998** [comment]
I have made an image based on pikvm. Just download blikvm-pikvm-v4.tar.gz and enjoy.

**Comment by s-e-t-h** [comment]
@RainCat1998 The image worked, thank you so much. Can I help with hosting the file in an EU location? The download speed will be slow for EU/NA users.

**Comment by jcastro** [comment]
@RainCat1998 amazing! I installed it a while back but noticed there's no way to update to the latest version of pikvm? or am I missing something?

**Comment by s-e-t-h** [comment]
@jcastro Could it work via a terminal command?

**Comment by jcastro** [comment]
<img width="436" alt="image" src="https://github.com/user-attachments/assets/568c3126-6fe7-401f-9dfc-2a9de3150bf7">

also getting this error when trying to upload something!

**Comment by jcastro** [comment]
> @jcastro Could it work via a terminal command?

no the commands are not available, at least the ones on the pikvm documentation

**Comment by RainCat1998** [comment]
> @RainCat1998 amazing! I installed it a while back but noticed there's no way to update to the latest version of pikvm? or am I missing something?

No, you can't. Allwiner's kernel is too old to support the latest pikvm packages.

**Comment by RainCat1998** [comment]
> <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/190036/368564557-568c3126-6fe7-401f-9dfc-2a9de3150bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTc2NDcsIm5iZiI6MTcyNzAxNzM0NywicGF0aCI6Ii8xOTAwMzYvMzY4NTY0NTU3LTU2OGMzMTI2LTZmZTctNDAxZi05ZGZjLTJhOWRlMzE1MGJmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNTAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzlkZGNkMjUxODM5MDg0MjMzMWRjYjg2NzIzYjM2MTE3YWVjMDk1OTUzZmY4NzM1NDc3ZmU5ODU2YzkwYzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b_nKcyJXtfVZ4QpCSkECgvK2fGm45lEt3nWuFsDapEI">
> also getting this error when trying to upload something!

You can try to reflash the image or recreate the MSD partition. It works fine on my board.

**Comment by jcastro** [comment]
> > <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/190036/368564557-568c3126-6fe7-401f-9dfc-2a9de3150bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTc2NDcsIm5iZiI6MTcyNzAxNzM0NywicGF0aCI6Ii8xOTAwMzYvMzY4NTY0NTU3LTU2OGMzMTI2LTZmZTctNDAxZi05ZGZjLTJhOWRlMzE1MGJmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNTAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzlkZGNkMjUxODM5MDg0MjMzMWRjYjg2NzIzYjM2MTE3YWVjMDk1OTUzZmY4NzM1NDc3ZmU5ODU2YzkwYzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b_nKcyJXtfVZ4QpCSkECgvK2fGm45lEt3nWuFsDapEI">
> > also getting this error when trying to upload something!
> 
> You can try to reflash the image or recreate the MSD partition. It works fine on my board.

Thanks! I tried to re-flash the image but still same problem

<img width="452" alt="image" src="https://github.com/user-attachments/assets/9a230504-5113-4581-a118-4aa1d75a7ae8">

Should I follow your tutorial on installing Pi-KVM on the Bli-KVM for the MSD partition creation?

**Comment by s-e-t-h** [comment]
> > @RainCat1998 amazing! I installed it a while back but noticed there's no way to update to the latest version of pikvm? or am I missing something?
> 
> No, you can't. Allwiner's kernel is too old to support the latest pikvm packages.

Even the 616?

What about their other products?

**Comment by RainCat1998** [comment]
> > > <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/190036/368564557-568c3126-6fe7-401f-9dfc-2a9de3150bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTc2NDcsIm5iZiI6MTcyNzAxNzM0NywicGF0aCI6Ii8xOTAwMzYvMzY4NTY0NTU3LTU2OGMzMTI2LTZmZTctNDAxZi05ZGZjLTJhOWRlMzE1MGJmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNTAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzlkZGNkMjUxODM5MDg0MjMzMWRjYjg2NzIzYjM2MTE3YWVjMDk1OTUzZmY4NzM1NDc3ZmU5ODU2YzkwYzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b_nKcyJXtfVZ4QpCSkECgvK2fGm45lEt3nWuFsDapEI">
> > > also getting this error when trying to upload something!
> > 
> > 
> > You can try to reflash the image or recreate the MSD partition. It works fine on my board.
> 
> Thanks! I tried to re-flash the image but still same problem
> 
> <img alt="image" width="452" src="https://private-user-images.githubusercontent.com/190036/369704687-9a230504-5113-4581-a118-4aa1d75a7ae8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODg5NDAsIm5iZiI6MTcyNzA4ODY0MCwicGF0aCI6Ii8xOTAwMzYvMzY5NzA0Njg3LTlhMjMwNTA0LTUxMTMtNDU4MS1hMTE4LTRhYTFkNzVhN2FlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMDUwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODk4YTc2ZWZlMDQ1YWJiYmFlNWE0ZTdmM2UzMGZlY2U4NzM3OWEwNjRiZDlhNTAxZWQ3YjUyMTk4MTJhOWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qTHHq2DBfK2-Q5Z_6eyJQKvo_wX4MCzYWbAocfmtddM">
> Should I follow your tutorial on installing Pi-KVM on the Bli-KVM for the MSD partition creation?

Yes, you can try to follow my guide. It works fine on my two BliKVM V4 boards.

**Comment by RainCat1998** [comment]
> > > @RainCat1998 amazing! I installed it a while back but noticed there's no way to update to the latest version of pikvm? or am I missing something?
> > 
> > 
> > No, you can't. Allwiner's kernel is too old to support the latest pikvm packages.
> 
> Even the 616?
> 
> What about their other products?

I only test it on blikvm V4.

**Comment by jcastro** [comment]
> > <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/190036/368564557-568c3126-6fe7-401f-9dfc-2a9de3150bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTc2NDcsIm5iZiI6MTcyNzAxNzM0NywicGF0aCI6Ii8xOTAwMzYvMzY4NTY0NTU3LTU2OGMzMTI2LTZmZTctNDAxZi05ZGZjLTJhOWRlMzE1MGJmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNTAyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzlkZGNkMjUxODM5MDg0MjMzMWRjYjg2NzIzYjM2MTE3YWVjMDk1OTUzZmY4NzM1NDc3ZmU5ODU2YzkwYzgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b_nKcyJXtfVZ4QpCSkECgvK2fGm45lEt3nWuFsDapEI">
> > also getting this error when trying to upload something!
> 
> You can try to reflash the image or recreate the MSD partition. It works fine on my board.

what's your SD size? I'm using 32GB

**Comment by bluegizmo83** [comment]
What is the terminal password for this image?? When I try to use the suggested `kvmd-htpasswd set admin` it says `PermissionError: [Errno 13] Permission denied: '/etc/kvmd/.htpasswd.kikvqq7z'` and when I try to do `sudo` or `su` it asks for a password, and I've tried:

- admin
- root
- 1234
- blank (i.e. not password)

**Comment by Arinono** [comment]
> What is the terminal password for this image?? When I try to use the suggested `kvmd-htpasswd set admin` it says `PermissionError: [Errno 13] Permission denied: '/etc/kvmd/.htpasswd.kikvqq7z'` and when I try to do `sudo` or `su` it asks for a password, and I've tried:
> 
> * admin
> * root
> * 1234
> * blank (i.e. not password)

`blikvm`
