### ISSUE TITLE
BLIKVM Allwinner - packages not found

### ISSUE THREAD

**Issue by xkoldxx** [RainCat1998/Bli-PiKVM#3]
while following your guide there are a number of packages to show 

E: Failed to fetch http://deb.volian.org/volian/pool/main/p/python-typing-extensions/python3-typing-extensions_4.4.0-1_all.deb  404  Not Found [IP: 99.118.93.168 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
apt

i have tried the pip install suggested in the other open issue but no luck 

is there any .bin precompiled

**Comment by RainCat1998** [comment]
You can use the out-of-the-box image  #1 OR manually install the missing packages.
